name: Generate terraform docs
on:
  # - pull_request
  - push
  - workflow_dispatch

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      # with:
      #   ref: ${{ github.event.pull_request.head.ref }}

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2

    - name: Generate diagram
      run: | 
        terraform init
        terraform graph | dot -Tpng >graph.png
      shell: bash
      working-directory: terraform/azure-devops/create-service-connection

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        config-file: doc-gen/.terraform-docs.yml
        working-dir: terraform/azure-devops/create-service-connection
        output-format: markdown table
        git-push: true

    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add graph.png
        git add README.md
        git diff-index --quiet HEAD || git commit -m "Update docs"
        git push
      shell: bash
      working-directory: terraform/azure-devops/create-service-connection